import type { LessonObject } from "@/types/lesson"

const lesson: LessonObject = {
  id: "l4-03-balance-sheet-cashflow",
  level: 4,
  order: 3,
  title: "Balance Sheet & Cash Flow Statement",
  subtitle: "Assets, liabilities, equity, and cash generation",
  xpReward: 28,
  body: `## The Balance Sheet

While the P&L shows what happened during a year, the **balance sheet shows the cumulative financial position** of the company from inception. It is prepared on a flow basis.

### The Fundamental Equation

**Assets = Liabilities**

Or equivalently:

**Shareholders' Equity = Assets − Liabilities**

Shareholders' equity (also called Net Worth) is the residual value left for shareholders after all obligations are paid.

### ARBL Balance Sheet Example (FY14)

**Liabilities Side** (how the company funds itself):
- Share Capital: ₹17.08 Crs (170,812,500 shares at ₹1 face value each)
- Reserves & Surplus: shareholders' retained earnings over the years
- Long-term borrowings
- Current liabilities (trade payables, short-term debt)

**Assets Side** (what the company owns):
- **Non-current assets**: Fixed assets (plants, machinery), intangible assets, long-term investments
- **Current assets**: Inventory, trade receivables, cash & equivalents

### Current vs Non-Current

| Type | Assets (examples) | Liabilities (examples) |
|---|---|---|
| **Current** (within 1 year) | Inventory, receivables, cash | Short-term debt, payables |
| **Non-current** (> 1 year) | Land, plant, machinery | Long-term debt |

---

## The Cash Flow Statement

The cash flow statement explains how cash moves in and out of the business. It has three sections:

### 1. Cash Flow from Operations (CFO)
Cash generated from the core business activity — most important section.
- A company with positive CFO is generating real cash, not just accounting profits
- CFO should be positive and growing — a red flag if PAT grows but CFO doesn't

### 2. Cash Flow from Investing (CFI)
Cash used for capital expenditure, buying/selling investments, acquiring companies.
- Typically negative for a growing company (investing in expansion)

### 3. Cash Flow from Financing (CFF)
Cash from raising debt/equity or repaying debt/paying dividends.

### Free Cash Flow (FCF)

FCF = CFO − Capital Expenditure

FCF represents cash left after maintaining and expanding the business — available to return to shareholders or reduce debt. High FCF = financially healthy company.

### The Connection Between Three Statements

The three statements are deeply linked:
- **P&L net profit** reconciles to **cash flow from operations** (after adjusting non-cash items like depreciation)
- **Balance sheet cash** = ending balance after all cash flows
- **Retained earnings** in balance sheet = cumulative P&L profits not paid as dividend

---

## Key Ratios from the Balance Sheet

**Debt-to-Equity Ratio** = Total Debt ÷ Shareholders' Equity
- A high D/E ratio means the company is highly leveraged — risky
- Prefer companies with D/E < 1

**Working Capital** = Current Assets − Current Liabilities
- Positive working capital = company can meet short-term obligations
- Negative working capital is a stress signal (except in special business models)`,

  keyTerms: [
    {
      term: "Balance Sheet",
      definition: "A financial statement showing a company's assets, liabilities, and shareholders' equity at a specific date. Total assets must always equal total liabilities + equity.",
    },
    {
      term: "Shareholders' Equity (Net Worth)",
      definition: "The residual value of the company belonging to shareholders. Equity = Assets − Liabilities. Includes paid-up share capital and retained earnings (reserves).",
    },
    {
      term: "Cash Flow from Operations (CFO)",
      definition: "Net cash generated by the core business. Must be positive and ideally growing. A company with growing PAT but declining CFO may be manipulating earnings.",
    },
    {
      term: "Free Cash Flow (FCF)",
      definition: "CFO minus capital expenditure. Cash available after maintaining and growing the business — the most accurate measure of a company's cash-generation power.",
    },
    {
      term: "Debt-to-Equity Ratio",
      definition: "Total Debt divided by Shareholders' Equity. Measures financial leverage. D/E < 1 preferred. High D/E = high interest burden = risky.",
    },
  ],

  facts: [
    {
      statement: "Balance sheet equation: Assets = Liabilities. Shareholders' equity = Assets − Liabilities. The balance sheet is always 'balanced'.",
      citation: "Varsity Module 3, Ch. 6.1",
    },
    {
      statement: "ARBL FY14 share capital = ₹17.081 Crs, representing 17,08,12,500 shares.",
      citation: "Varsity Module 3, Ch. 6",
    },
    {
      statement: "Cash flow statement has three sections: Operations (CFO), Investing (CFI), and Financing (CFF). CFO must be positive for a company to be generating real cash.",
      citation: "Varsity Module 3, Ch. 8",
    },
    {
      statement: "Free Cash Flow (FCF) = Cash Flow from Operations − Capital Expenditure. FCF represents cash available after business investment.",
      citation: "Varsity Module 3, Ch. 8",
    },
    {
      statement: "The 10-point investment checklist requires cash flow from operations to be positive — a company not generating operating cash is showing operating stress.",
      citation: "Varsity Module 3, Ch. 12.4",
    },
  ],

  quizSeed: [
    {
      id: "l4-03-q1",
      question: "If a company's total assets are ₹500 Crs and total liabilities are ₹320 Crs, what is shareholders' equity?",
      options: ["₹820 Crs", "₹500 Crs", "₹320 Crs", "₹180 Crs"],
      correct: 3,
      explanation: "Shareholders' Equity = Assets − Liabilities = 500 − 320 = ₹180 Crs.",
      difficulty: "easy",
      citation: "Varsity Module 3, Ch. 6.1",
    },
    {
      id: "l4-03-q2",
      question: "Which section of the cash flow statement is most important for assessing business health?",
      options: [
        "Cash Flow from Investing",
        "Cash Flow from Financing",
        "Cash Flow from Operations",
        "Free Cash Flow section",
      ],
      correct: 2,
      explanation: "Cash Flow from Operations (CFO) shows cash generated by the core business. A company with positive and growing CFO is financially healthy.",
      difficulty: "easy",
      citation: "Varsity Module 3, Ch. 8",
    },
    {
      id: "l4-03-q3",
      question: "How is Free Cash Flow (FCF) calculated?",
      options: [
        "PAT minus dividends paid",
        "CFO minus capital expenditure",
        "Total revenue minus total expenses",
        "EBITDA minus interest and taxes",
      ],
      correct: 1,
      explanation: "FCF = Cash Flow from Operations − Capital Expenditure. It represents cash left after investing in the business's maintenance and growth.",
      difficulty: "medium",
      citation: "Varsity Module 3, Ch. 8",
    },
    {
      id: "l4-03-q4",
      question: "The balance sheet shows the company's financial position:",
      options: [
        "For an entire financial year (flow basis)",
        "As of a specific date (stock/snapshot basis)",
        "For the quarter just ended",
        "Cumulative since IPO only",
      ],
      correct: 1,
      explanation: "The balance sheet is a snapshot at a specific date (e.g., 31 March 2014). The P&L covers an entire year. The balance sheet is prepared on a flow/cumulative basis since inception.",
      difficulty: "medium",
      citation: "Varsity Module 3, Ch. 6.1",
    },
    {
      id: "l4-03-q5",
      question: "A company reports PAT growth of 25% but cash flow from operations is negative. What does this signal?",
      options: [
        "The company is investing heavily in expansion",
        "Potential earnings manipulation — cash generation doesn't match profits",
        "The company is paying large dividends",
        "Normal for a capital-intensive business",
      ],
      correct: 1,
      explanation: "Growing PAT with negative/declining CFO is a key red flag — it suggests earnings may be manipulated through accounting adjustments rather than real cash generation.",
      difficulty: "hard",
      citation: "Varsity Module 3, Ch. 12.4",
    },
  ],

  attribution: "Content sourced from Zerodha Varsity Module 3 — Fundamental Analysis (zerodha.com/varsity)",
}

export default lesson
