import type { LessonObject } from "@/types/lesson"

const lesson: LessonObject = {
  id: "l3-04-moving-averages",
  level: 3,
  order: 4,
  title: "Moving Averages",
  subtitle: "SMA, EMA, and crossover trading systems",
  xpReward: 28,
  body: `## What is a Moving Average?

A moving average smooths out price data by calculating the average closing price over a rolling window of time. As each new day's data arrives, the oldest day is dropped — the window "moves" forward.

**Example — ITC 5-day average (14–18 Jul 2014)**:
Closing prices: 344.95, 342.35, 344.20, 344.25, 344.0 → Total = 1179.75 → Average = **343.95**

**Example — Marico 5-day (21–25 Jul 2014)**:
239.2, 240.6, 241.8, 242.8, 247.9 → Total = 1212.3 → Average = **242.5**

On 28 Jul, we drop 21 Jul and add 28 Jul (250.2): new 5-day average = 1223.3 / 5 = **244.66**. The average "moves" with time — hence the name.

## Simple Moving Average (SMA)

The SMA gives equal weight to every data point in the window. A **5-day SMA** uses 5 data points; a **50-day SMA** uses 50.

## Exponential Moving Average (EMA)

The EMA gives more weight to recent data points. Because TA assumes the latest price discounts all information, recent prices matter more. The EMA reacts faster to current price changes than the SMA.

**Key rule**: For all practical purposes, use EMA over SMA.

## Basic Trading Signal

- **Price > EMA**: Traders are willing to buy above the average → bullish outlook → look to buy.
- **Price < EMA**: Traders are willing to sell below the average → bearish outlook → look to sell.

**50-day EMA system on Ambuja Cements**:
- B1@165 → S1@187: +₹22 (13%)
- B2@178 → S2@182: +₹4 (2.2%)
- B3@165 → S3@215: +₹50 (30%)

The 2nd trade was small because the market was sideways — MA works best in trending markets.

## The Problem: Sideways Markets

In sideways (range-bound) markets, a single MA generates too many small losing trades (called "whipsaws") before the big trending trade arrives. The solution is the **MA Crossover System**.

## MA Crossover System

Combine two EMAs — a faster (shorter) and a slower (longer):
- **Buy**: when the faster EMA crosses above the slower EMA
- **Exit long**: when the faster EMA crosses below the slower EMA

Popular combinations:
| Combination | Use case |
|---|---|
| 9-day × 21-day EMA | Short-term trades (days) |
| 25-day × 50-day EMA | Medium-term trades (weeks) |
| 50-day × 100-day EMA | Trades lasting months |
| 100-day × 200-day EMA | Long-term investments (1+ year) |

The crossover system gives fewer signals than a single MA, but a higher proportion are profitable — it keeps you out of sideways chop.

## Key Insight

Moving averages are a **trend-following system**. They work brilliantly in a trending market and poorly in a sideways one. The trader's job is to stay patient through the small losing trades, knowing the one big trending trade will more than compensate.`,

  keyTerms: [
    {
      term: "Simple Moving Average (SMA)",
      definition: "An average of the closing prices over N days where each day gets equal weight. Updates by dropping the oldest data point and adding the newest.",
    },
    {
      term: "Exponential Moving Average (EMA)",
      definition: "A moving average that gives more weight to recent prices. Reacts faster to current market conditions than SMA. Preferred for trading.",
    },
    {
      term: "MA Crossover System",
      definition: "A trading system using two EMAs (fast and slow). Buy when fast EMA crosses above slow EMA; exit when fast crosses below slow. Reduces whipsaws in sideways markets.",
    },
    {
      term: "Whipsaw",
      definition: "A false trading signal generated by an indicator during a sideways market — causing the trader to enter and exit repeatedly for small losses.",
    },
  ],

  facts: [
    {
      statement: "ITC 5-day SMA (14–18 Jul 2014): closing prices 344.95, 342.35, 344.20, 344.25, 344.0 → average = 343.95.",
      citation: "Varsity Module 2, Ch. 13",
    },
    {
      statement: "Marico 5-day SMA (21–25 Jul 2014): 239.2, 240.6, 241.8, 242.8, 247.9 → average = 242.5; on 28 Jul the new average = 244.66.",
      citation: "Varsity Module 2, Ch. 13.1",
    },
    {
      statement: "50-day EMA system on Ambuja Cements generated three trades: B1@165→S1@187 (+13%), B2@178→S2@182 (+2.2%), B3@165→S3@215 (+30%).",
      citation: "Varsity Module 2, Ch. 13.3",
    },
    {
      statement: "Moving averages work brilliantly in trending markets but generate frequent whipsaws in sideways markets.",
      citation: "Varsity Module 2, Ch. 13.3",
    },
    {
      statement: "EMA is preferred over SMA because it gives more weight to the most recent data points, making it more reactive to current price.",
      citation: "Varsity Module 2, Ch. 13.2",
    },
    {
      statement: "Popular MA crossover combinations: 9×21 day (short-term), 25×50 day (medium-term), 50×100 day (months), 100×200 day (long-term investments).",
      citation: "Varsity Module 2, Ch. 13.4",
    },
  ],

  quizSeed: [
    {
      id: "l3-04-q1",
      question: "What is the 5-day SMA of ITC based on closing prices 344.95, 342.35, 344.20, 344.25, 344.0?",
      options: ["342.5", "343.95", "344.25", "345.0"],
      correct: 1,
      explanation: "Sum = 1179.75 ÷ 5 = 343.95. This is the simple average of the five closing prices.",
      difficulty: "easy",
      citation: "Varsity Module 2, Ch. 13",
    },
    {
      id: "l3-04-q2",
      question: "Why is EMA preferred over SMA for trading?",
      options: [
        "EMA is easier to calculate manually",
        "EMA gives equal weight to all data points",
        "EMA gives more weight to recent prices, making it more reactive",
        "EMA always generates fewer signals",
      ],
      correct: 2,
      explanation: "EMA assigns greater weight to recent data points, making it quicker to react to current price changes — aligned with TA's assumption that recent price discounts all information.",
      difficulty: "easy",
      citation: "Varsity Module 2, Ch. 13.2",
    },
    {
      id: "l3-04-q3",
      question: "In a MA crossover system, when should you buy?",
      options: [
        "When price crosses above the 50-day EMA",
        "When the faster EMA crosses above the slower EMA",
        "When volume increases above average",
        "When RSI drops below 30",
      ],
      correct: 1,
      explanation: "In a crossover system, a buy signal is triggered when the faster (shorter period) EMA crosses above the slower (longer period) EMA.",
      difficulty: "medium",
      citation: "Varsity Module 2, Ch. 13.4",
    },
    {
      id: "l3-04-q4",
      question: "Moving averages perform poorly in which type of market?",
      options: [
        "Strongly trending upmarket",
        "Strongly trending downmarket",
        "Sideways (range-bound) market",
        "Volatile market with large daily swings",
      ],
      correct: 2,
      explanation: "In sideways markets, MAs generate frequent whipsaws — multiple small losing trades — because there is no sustained trend to follow.",
      difficulty: "medium",
      citation: "Varsity Module 2, Ch. 13.3",
    },
    {
      id: "l3-04-q5",
      question: "Which MA crossover combination is best suited for identifying long-term investment opportunities lasting over a year?",
      options: [
        "9-day × 21-day EMA",
        "25-day × 50-day EMA",
        "50-day × 100-day EMA",
        "100-day × 200-day EMA",
      ],
      correct: 3,
      explanation: "The 100×200 day EMA crossover is used for long-term trades and investment opportunities, some lasting over a year.",
      difficulty: "medium",
      citation: "Varsity Module 2, Ch. 13.4",
    },
  ],

  attribution: "Content sourced from Zerodha Varsity Module 2 — Technical Analysis (zerodha.com/varsity)",
}

export default lesson
